# Generated by Django 6.0.2 on 2026-04-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-imported_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='sales_batch_month_between_1_12'), models.CheckConstraint(condition=models.Q(('year__gte', 2000)), name='sales_batch_year_gte_2000'), models.CheckConstraint(condition=models.Q(('file_name', ''), _negated=True), name='sales_batch_file_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('units_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='catalog.productvariant')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='sales.salesimportbatch')),
            ],
            options={
                'ordering': ['-sale_date', 'product_name', 'variant_name'],
                'constraints': [models.UniqueConstraint(fields=('sale_date', 'variant'), name='uniq_daily_sale_per_variant_per_day'), models.CheckConstraint(condition=models.Q(('units_sold__gte', 0)), name='daily_sale_units_sold_gte_0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='daily_sale_unit_price_gte_0'), models.CheckConstraint(condition=models.Q(('daily_revenue__gte', 0)), name='daily_sale_daily_revenue_gte_0'), models.CheckConstraint(condition=models.Q(('product_name', ''), _negated=True), name='daily_sale_product_name_not_empty'), models.CheckConstraint(condition=models.Q(('variant_name', ''), _negated=True), name='daily_sale_variant_name_not_empty')],
            },
        ),
    ]
