# Generated by Django 6.0.2 on 2026-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_add_ticket_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="case_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
