# Generated by Django 6.0.2 on 2026-02-21 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+\\-\\s()]*$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='State must be a 2-letter uppercase abbreviation (e.g., NC).', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Zipcode must be 5 digits or ZIP+4 (e.g., 27502 or 27502-1234).', regex='^\\d{5}(-\\d{4})?$')]),
        ),
    ]
