# Generated by Django 6.0.2 on 2026-02-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customerprofile_phone_and_more'),
        ('accounts', '0002_userrole_delete_userprofile'),
    ]

    operations = [
    ]
