# Generated by Django 6.0.2 on 2026-02-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
