# Generated by Django 6.0.2 on 2026-03-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_email_verified'),
        ('accounts', '0005_customerprofile_email_verified'),
    ]

    operations = [
    ]
