# Generated by Django 6.0.2 on 2026-03-06 01:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260305_1944'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits, optional +country code).', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, validators=[django.core.validators.RegexValidator(message='State must be a 2-letter uppercase code (e.g., NC).', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid ZIP code (e.g., 12345 or 12345-6789).', regex='^\\d{5}(-\\d{4})?$')]),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BUSINESS', 'Business'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
