# Generated by Django 6.0.2 on 2026-05-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_executive_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("BUSINESS", "Business"),
                    ("CUSTOMER", "Customer"),
                    ("EXECUTIVE", "Executive"),
                    ("SUPPORT", "Support"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
