# Generated by Django 6.0.2 on 2026-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userrole_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("BUSY", "Busy"),
                    ("AWAY", "Away"),
                ],
                default="OFFLINE",
                max_length=10,
            ),
        ),
    ]
