# Generated by Django 6.0.2 on 2026-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_options_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='supplier_name_not_empty'),
        ),
    ]
