# Generated by Django 6.0.2 on 2026-02-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_of_measure', models.CharField(choices=[('units', 'Units'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('ml', 'Milliliters'), ('l', 'Liters')], default='units', max_length=10)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierInventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_usages', to='inventory.inventoryitem')),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usage', to='catalog.modifieroption')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('modifier_option', 'inventory_item'), name='uniq_inventory_item_per_modifier_option')],
            },
        ),
        migrations.CreateModel(
            name='VariantInventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_usages', to='inventory.inventoryitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usage', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variant', 'inventory_item'), name='uniq_inventory_item_per_variant_recipe')],
            },
        ),
    ]
