# Generated by Django 6.0.2 on 2026-04-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventoryitem_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventoryitem",
            name="inv_item_stock_qty_gte_reorder_level",
        ),
    ]
