# Generated by Django 6.0.2 on 2026-04-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_inventoryitem_inv_item_stock_qty_gte_reorder_level"),
        ("suppliers", "0005_alter_supplier_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="suppliers.supplier",
            ),
        ),
    ]
