# Generated by Django 6.0.2 on 2026-06-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_inventoryitem_supplier"),
        ("locations", "0003_stateprovince_location_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreInventoryLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_levels",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_levels",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "ordering": ["inventory_item__name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("stock_quantity__gte", 0)),
                        name="store_inv_level_stock_qty_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reorder_level__isnull", True),
                            ("reorder_level__gte", 0),
                            _connector="OR",
                        ),
                        name="store_inv_level_reorder_gte_0_or_null",
                    ),
                ],
                "unique_together": {("store", "inventory_item")},
            },
        ),
    ]
