# Generated by Django 6.0.2 on 2026-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole_delete_userprofile'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_requires_customer_or_guest_email',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('customer__isnull', False), ('guest_email__isnull', True)), models.Q(('customer__isnull', True), ('guest_email__isnull', False)), _connector='OR'), name='order_customer_xor_guest_email'),
        ),
    ]
