# Generated by Django 6.0.2 on 2026-02-25 14:11

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_delete_userrole'),
        ('catalog', '0002_alter_category_options'),
        ('orders', '0002_remove_order_order_requires_customer_or_guest_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='order_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', 0)), name='order_tax_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_payment_due__gte', 0)), name='order_total_payment_due_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_payment_due', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('tax_amount')))), name='order_total_equals_subtotal_plus_tax'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price_charged__gte', 0)), name='order_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('item_total__gte', 0)), name='order_item_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('item_total', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price_charged')))), name='order_item_total_equals_qty_times_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='orderitemmodifier',
            constraint=models.CheckConstraint(check=models.Q(('price_adjustment_charged__gte', 0)), name='order_item_modifier_price_adj_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='payment_total_gte_0'),
        ),
    ]
