# Generated by Django 6.0.2 on 2026-03-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customerprofile_created_at_and_more'),
        ('orders', '0003_order_order_subtotal_gte_0_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('customer',), name='uniq_draft_order_per_customer'),
        ),
    ]
