# Generated by Django 6.0.2 on 2026-03-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_id_alter_orderitem_id_and_more"),
        ("orders", "0004_order_uniq_draft_order_per_customer"),
    ]

    operations = []
