# Generated by Django 6.0.2 on 2026-03-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodifier',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
