# Generated by Django 6.0.2 on 2026-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitemmodifier_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodifier',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
