# Generated by Django 6.0.2 on 2026-04-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_orderitemmodifier_quantity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="order_total_equals_subtotal_plus_tax",
        ),
    ]
