# Generated by Django 6.0.2 on 2026-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hq_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
