# Generated by Django 6.0.2 on 2026-04-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_storesettings_store_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="show_tagline",
            field=models.BooleanField(default=True),
        ),
    ]
