# Generated by Django 6.0.2 on 2026-03-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_id_alter_modifiergroup_id_and_more"),
        ("catalog", "0003_product_description"),
    ]

    operations = []
