# Generated by Django 6.0.2 on 2026-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_stateprovince_location_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="opening_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
